-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified_rcv_enclave_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace verified_rcv_enclave_core

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2466:4-2473:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2485:4-2494:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish"]
axiom core.fmt.Formatter.debug_struct_field3_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Debug for (U, T)}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3082:16-3082:62
    Name pattern: [core::fmt::{core::fmt::Debug<(@U, @T)>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Debug<(@U, @T)>}::fmt"]
axiom Pair.Insts.CoreFmtDebug.fmt
  {U : Type} {T : Type} (DebugInst : core.fmt.Debug U) (DebugInst1 :
  core.fmt.Debug T) :
  (U × T) → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::fmt::{core::fmt::Debug for (U, T)}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3080:12-3080:57
    Name pattern: [core::fmt::Debug<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<(@U, @T)>"]
def Pair.Insts.CoreFmtDebug {U : Type} {T : Type} (DebugInst : core.fmt.Debug
  U) (DebugInst1 : core.fmt.Debug T) : core.fmt.Debug (U × T) := {
  fmt := Pair.Insts.CoreFmtDebug.fmt DebugInst DebugInst1
}

/-- [core::tuple::{core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- Trait implementation: [core::tuple::{core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
}

/-- [alloc::string::{core::cmp::PartialEq<alloc::string::String> for alloc::string::String}::eq]:
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::cmp::PartialEq<alloc::string::String, alloc::string::String>}::eq"]
axiom alloc.string.String.Insts.CoreCmpPartialEqString.eq
  : String → String → Result Bool

/-- Trait implementation: [alloc::string::{core::cmp::PartialEq<alloc::string::String> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [core::cmp::PartialEq<alloc::string::String, alloc::string::String>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloc::string::String, alloc::string::String>"]
def alloc.string.String.Insts.CoreCmpPartialEqString : core.cmp.PartialEq
  String String := {
  eq := alloc.string.String.Insts.CoreCmpPartialEqString.eq
}

/-- [alloc::string::{core::clone::Clone for alloc::string::String}::clone]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2351:4-2351:27
    Name pattern: [alloc::string::{core::clone::Clone<alloc::string::String>}::clone]
    Visibility: public -/
@[rust_fun "alloc::string::{core::clone::Clone<alloc::string::String>}::clone"]
axiom alloc.string.String.Insts.CoreCloneClone.clone : String → Result String

/-- Trait implementation: [alloc::string::{core::clone::Clone for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2350:0-2350:21
    Name pattern: [core::clone::Clone<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::clone::Clone<alloc::string::String>"]
def alloc.string.String.Insts.CoreCloneClone : core.clone.Clone String := {
  clone := alloc.string.String.Insts.CoreCloneClone.clone
}

/-- [alloc::string::{core::fmt::Debug for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2721:4-2721:60
    Name pattern: [alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDebug.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [alloc::string::{core::fmt::Debug for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2719:0-2719:26
    Name pattern: [core::fmt::Debug<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<alloc::string::String>"]
def alloc.string.String.Insts.CoreFmtDebug : core.fmt.Debug String := {
  fmt := alloc.string.String.Insts.CoreFmtDebug.fmt
}

/-- [verified_rcv_enclave_core::Ballot]
    Source: 'crates/enclave-core/src/lib.rs', lines 46:0-48:1
    Visibility: public -/
structure Ballot where
  ranking : alloc.vec.Vec String

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::Ballot}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 45:9-45:14
    Visibility: public -/
def Ballot.Insts.CoreCloneClone.clone (self : Ballot) : Result Ballot := do
  let v ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.ranking
  ok { ranking := v }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::Ballot}]
    Source: 'crates/enclave-core/src/lib.rs', lines 45:9-45:14 -/
@[reducible]
def Ballot.Insts.CoreCloneClone : core.clone.Clone Ballot := {
  clone := Ballot.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::Ballot}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 45:16-45:21
    Visibility: public -/
def Ballot.Insts.CoreFmtDebug.fmt
  (self : Ballot) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
      alloc.string.String.Insts.CoreFmtDebug)) self.ranking
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "Ballot") (toStr
    "ranking") dyn

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::Ballot}]
    Source: 'crates/enclave-core/src/lib.rs', lines 45:16-45:21 -/
@[reducible]
def Ballot.Insts.CoreFmtDebug : core.fmt.Debug Ballot := {
  fmt := Ballot.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::Ballot}]
    Source: 'crates/enclave-core/src/lib.rs', lines 45:23-45:32 -/
@[reducible]
def Ballot.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Ballot := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::Ballot> for verified_rcv_enclave_core::Ballot}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 45:23-45:32
    Visibility: public -/
def Ballot.Insts.CoreCmpPartialEqBallot.eq
  (self : Ballot) (other : Ballot) : Result Bool := do
  alloc.vec.partial_eq.PartialEqVec.eq
    alloc.string.String.Insts.CoreCmpPartialEqString self.ranking other.ranking

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::Ballot> for verified_rcv_enclave_core::Ballot}]
    Source: 'crates/enclave-core/src/lib.rs', lines 45:23-45:32 -/
@[reducible]
def Ballot.Insts.CoreCmpPartialEqBallot : core.cmp.PartialEq Ballot Ballot := {
  eq := Ballot.Insts.CoreCmpPartialEqBallot.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::Ballot}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 45:34-45:36
    Visibility: public -/
def Ballot.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : Ballot) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::Ballot}]
    Source: 'crates/enclave-core/src/lib.rs', lines 45:34-45:36 -/
@[reducible]
def Ballot.Insts.CoreCmpEq : core.cmp.Eq Ballot := {
  partialEqInst := Ballot.Insts.CoreCmpPartialEqBallot
  assert_receiver_is_total_eq :=
    Ballot.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::RawEntry]
    Source: 'crates/enclave-core/src/lib.rs', lines 60:0-63:1
    Visibility: public -/
structure RawEntry where
  voter : String
  ciphertext : alloc.vec.Vec Std.U8

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::RawEntry}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 59:9-59:14
    Visibility: public -/
def RawEntry.Insts.CoreCloneClone.clone
  (self : RawEntry) : Result RawEntry := do
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self.voter
  let v ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.ciphertext
  ok { voter := s, ciphertext := v }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::RawEntry}]
    Source: 'crates/enclave-core/src/lib.rs', lines 59:9-59:14 -/
@[reducible]
def RawEntry.Insts.CoreCloneClone : core.clone.Clone RawEntry := {
  clone := RawEntry.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::RawEntry}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 59:16-59:21
    Visibility: public -/
def RawEntry.Insts.CoreFmtDebug.fmt
  (self : RawEntry) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ alloc.string.String.Insts.CoreFmtDebug self.voter
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec core.fmt.DebugU8))
      self.ciphertext
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "RawEntry") (toStr
    "voter") dyn (toStr "ciphertext") dyn1

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::RawEntry}]
    Source: 'crates/enclave-core/src/lib.rs', lines 59:16-59:21 -/
@[reducible]
def RawEntry.Insts.CoreFmtDebug : core.fmt.Debug RawEntry := {
  fmt := RawEntry.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::RawEntry}]
    Source: 'crates/enclave-core/src/lib.rs', lines 59:23-59:32 -/
@[reducible]
def RawEntry.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RawEntry := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::RawEntry> for verified_rcv_enclave_core::RawEntry}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 59:23-59:32
    Visibility: public -/
def RawEntry.Insts.CoreCmpPartialEqRawEntry.eq
  (self : RawEntry) (other : RawEntry) : Result Bool := do
  let b ←
    alloc.string.String.Insts.CoreCmpPartialEqString.eq self.voter other.voter
  if b
  then
    alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU8 self.ciphertext
      other.ciphertext
  else ok false

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::RawEntry> for verified_rcv_enclave_core::RawEntry}]
    Source: 'crates/enclave-core/src/lib.rs', lines 59:23-59:32 -/
@[reducible]
def RawEntry.Insts.CoreCmpPartialEqRawEntry : core.cmp.PartialEq RawEntry
  RawEntry := {
  eq := RawEntry.Insts.CoreCmpPartialEqRawEntry.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::RawEntry}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 59:34-59:36
    Visibility: public -/
def RawEntry.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : RawEntry) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::RawEntry}]
    Source: 'crates/enclave-core/src/lib.rs', lines 59:34-59:36 -/
@[reducible]
def RawEntry.Insts.CoreCmpEq : core.cmp.Eq RawEntry := {
  partialEqInst := RawEntry.Insts.CoreCmpPartialEqRawEntry
  assert_receiver_is_total_eq :=
    RawEntry.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::RoundCount]
    Source: 'crates/enclave-core/src/lib.rs', lines 81:0-84:1
    Visibility: public -/
structure RoundCount where
  candidate : String
  count : Std.U32

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::RoundCount}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 80:9-80:14
    Visibility: public -/
def RoundCount.Insts.CoreCloneClone.clone
  (self : RoundCount) : Result RoundCount := do
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self.candidate
  let i ← lift (core.clone.impls.CloneU32.clone self.count)
  ok { candidate := s, count := i }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::RoundCount}]
    Source: 'crates/enclave-core/src/lib.rs', lines 80:9-80:14 -/
@[reducible]
def RoundCount.Insts.CoreCloneClone : core.clone.Clone RoundCount := {
  clone := RoundCount.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::RoundCount}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 80:16-80:21
    Visibility: public -/
def RoundCount.Insts.CoreFmtDebug.fmt
  (self : RoundCount) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ alloc.string.String.Insts.CoreFmtDebug self.candidate
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.count
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "RoundCount") (toStr
    "candidate") dyn (toStr "count") dyn1

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::RoundCount}]
    Source: 'crates/enclave-core/src/lib.rs', lines 80:16-80:21 -/
@[reducible]
def RoundCount.Insts.CoreFmtDebug : core.fmt.Debug RoundCount := {
  fmt := RoundCount.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::RoundCount}]
    Source: 'crates/enclave-core/src/lib.rs', lines 80:23-80:32 -/
@[reducible]
def RoundCount.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RoundCount := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::RoundCount> for verified_rcv_enclave_core::RoundCount}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 80:23-80:32
    Visibility: public -/
def RoundCount.Insts.CoreCmpPartialEqRoundCount.eq
  (self : RoundCount) (other : RoundCount) : Result Bool := do
  if self.count = other.count
  then
    alloc.string.String.Insts.CoreCmpPartialEqString.eq self.candidate
      other.candidate
  else ok false

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::RoundCount> for verified_rcv_enclave_core::RoundCount}]
    Source: 'crates/enclave-core/src/lib.rs', lines 80:23-80:32 -/
@[reducible]
def RoundCount.Insts.CoreCmpPartialEqRoundCount : core.cmp.PartialEq RoundCount
  RoundCount := {
  eq := RoundCount.Insts.CoreCmpPartialEqRoundCount.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::RoundCount}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 80:34-80:36
    Visibility: public -/
def RoundCount.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : RoundCount) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::RoundCount}]
    Source: 'crates/enclave-core/src/lib.rs', lines 80:34-80:36 -/
@[reducible]
def RoundCount.Insts.CoreCmpEq : core.cmp.Eq RoundCount := {
  partialEqInst := RoundCount.Insts.CoreCmpPartialEqRoundCount
  assert_receiver_is_total_eq :=
    RoundCount.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::IRVResult]
    Source: 'crates/enclave-core/src/lib.rs', lines 98:0-103:1
    Visibility: public -/
structure IRVResult where
  winners : alloc.vec.Vec String
  per_round_counts : alloc.vec.Vec (alloc.vec.Vec RoundCount)
  eliminated_by_round : alloc.vec.Vec (alloc.vec.Vec String)
  ballots_tallied : Std.U32

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::IRVResult}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 97:9-97:14
    Visibility: public -/
def IRVResult.Insts.CoreCloneClone.clone
  (self : IRVResult) : Result IRVResult := do
  let v ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.winners
  let v1 ←
    alloc.vec.CloneVec.clone (core.clone.CloneallocvecVec
      RoundCount.Insts.CoreCloneClone) self.per_round_counts
  let v2 ←
    alloc.vec.CloneVec.clone (core.clone.CloneallocvecVec
      alloc.string.String.Insts.CoreCloneClone) self.eliminated_by_round
  let i ← lift (core.clone.impls.CloneU32.clone self.ballots_tallied)
  ok
    {
      winners := v,
      per_round_counts := v1,
      eliminated_by_round := v2,
      ballots_tallied := i
    }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::IRVResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 97:9-97:14 -/
@[reducible]
def IRVResult.Insts.CoreCloneClone : core.clone.Clone IRVResult := {
  clone := IRVResult.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::IRVResult}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 97:16-97:21
    Visibility: public -/
def IRVResult.Insts.CoreFmtDebug.fmt
  (self : IRVResult) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugVec alloc.string.String.Insts.CoreFmtDebug)
      self.winners
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugVec (core.fmt.DebugVec
      RoundCount.Insts.CoreFmtDebug)) self.per_round_counts
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugVec (core.fmt.DebugVec
      alloc.string.String.Insts.CoreFmtDebug)) self.eliminated_by_round
  let dyn3 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.ballots_tallied
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "IRVResult") (toStr
    "winners") dyn (toStr "per_round_counts") dyn1 (toStr
    "eliminated_by_round") dyn2 (toStr "ballots_tallied") dyn3

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::IRVResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 97:16-97:21 -/
@[reducible]
def IRVResult.Insts.CoreFmtDebug : core.fmt.Debug IRVResult := {
  fmt := IRVResult.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::IRVResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 97:23-97:32 -/
@[reducible]
def IRVResult.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq IRVResult := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::IRVResult> for verified_rcv_enclave_core::IRVResult}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 97:23-97:32
    Visibility: public -/
def IRVResult.Insts.CoreCmpPartialEqIRVResult.eq
  (self : IRVResult) (other : IRVResult) : Result Bool := do
  if self.ballots_tallied = other.ballots_tallied
  then
    let b ←
      alloc.vec.partial_eq.PartialEqVec.eq
        alloc.string.String.Insts.CoreCmpPartialEqString self.winners
        other.winners
    if b
    then
      let b1 ←
        alloc.vec.partial_eq.PartialEqVec.eq (core.cmp.PartialEqVec
          RoundCount.Insts.CoreCmpPartialEqRoundCount) self.per_round_counts
          other.per_round_counts
      if b1
      then
        alloc.vec.partial_eq.PartialEqVec.eq (core.cmp.PartialEqVec
          alloc.string.String.Insts.CoreCmpPartialEqString)
          self.eliminated_by_round other.eliminated_by_round
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::IRVResult> for verified_rcv_enclave_core::IRVResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 97:23-97:32 -/
@[reducible]
def IRVResult.Insts.CoreCmpPartialEqIRVResult : core.cmp.PartialEq IRVResult
  IRVResult := {
  eq := IRVResult.Insts.CoreCmpPartialEqIRVResult.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::IRVResult}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 97:34-97:36
    Visibility: public -/
def IRVResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : IRVResult) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::IRVResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 97:34-97:36 -/
@[reducible]
def IRVResult.Insts.CoreCmpEq : core.cmp.Eq IRVResult := {
  partialEqInst := IRVResult.Insts.CoreCmpPartialEqIRVResult
  assert_receiver_is_total_eq :=
    IRVResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::TallyResult]
    Source: 'crates/enclave-core/src/lib.rs', lines 115:0-123:1
    Visibility: public -/
structure TallyResult where
  winners : alloc.vec.Vec String
  per_round_counts : alloc.vec.Vec (alloc.vec.Vec RoundCount)
  eliminated_by_round : alloc.vec.Vec (alloc.vec.Vec String)
  ballots_tallied : Std.U32
  ballots_dropped : Std.U32
  dropped_voters : alloc.vec.Vec String
  non_voters : alloc.vec.Vec String

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::TallyResult}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 114:9-114:14
    Visibility: public -/
def TallyResult.Insts.CoreCloneClone.clone
  (self : TallyResult) : Result TallyResult := do
  let v ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.winners
  let v1 ←
    alloc.vec.CloneVec.clone (core.clone.CloneallocvecVec
      RoundCount.Insts.CoreCloneClone) self.per_round_counts
  let v2 ←
    alloc.vec.CloneVec.clone (core.clone.CloneallocvecVec
      alloc.string.String.Insts.CoreCloneClone) self.eliminated_by_round
  let i ← lift (core.clone.impls.CloneU32.clone self.ballots_tallied)
  let i1 ← lift (core.clone.impls.CloneU32.clone self.ballots_dropped)
  let v3 ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.dropped_voters
  let v4 ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.non_voters
  ok
    {
      winners := v,
      per_round_counts := v1,
      eliminated_by_round := v2,
      ballots_tallied := i,
      ballots_dropped := i1,
      dropped_voters := v3,
      non_voters := v4
    }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::TallyResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 114:9-114:14 -/
@[reducible]
def TallyResult.Insts.CoreCloneClone : core.clone.Clone TallyResult := {
  clone := TallyResult.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::TallyResult}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 114:16-114:21
    Visibility: public -/
def TallyResult.Insts.CoreFmtDebug.fmt
  (self : TallyResult) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugVec alloc.string.String.Insts.CoreFmtDebug)
      self.winners
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugVec (core.fmt.DebugVec
      RoundCount.Insts.CoreFmtDebug)) self.per_round_counts
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugVec (core.fmt.DebugVec
      alloc.string.String.Insts.CoreFmtDebug)) self.eliminated_by_round
  let dyn3 := Dyn.mk _ core.fmt.DebugU32 self.ballots_tallied
  let dyn4 := Dyn.mk _ core.fmt.DebugU32 self.ballots_dropped
  let dyn5 :=
    Dyn.mk _ (core.fmt.DebugVec alloc.string.String.Insts.CoreFmtDebug)
      self.dropped_voters
  let dyn6 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
      alloc.string.String.Insts.CoreFmtDebug)) self.non_voters
  let values :=
    Array.to_slice
      (Array.make 7#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5, dyn6 ])
  let s ←
    lift (Array.to_slice
      (Array.make 7#usize [
        toStr "winners", toStr "per_round_counts", toStr "eliminated_by_round",
        toStr "ballots_tallied", toStr "ballots_dropped", toStr
        "dropped_voters", toStr "non_voters"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "TallyResult") s
    values

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::TallyResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 114:16-114:21 -/
@[reducible]
def TallyResult.Insts.CoreFmtDebug : core.fmt.Debug TallyResult := {
  fmt := TallyResult.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::TallyResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 114:23-114:32 -/
@[reducible]
def TallyResult.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq TallyResult := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::TallyResult> for verified_rcv_enclave_core::TallyResult}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 114:23-114:32
    Visibility: public -/
def TallyResult.Insts.CoreCmpPartialEqTallyResult.eq
  (self : TallyResult) (other : TallyResult) : Result Bool := do
  if self.ballots_tallied = other.ballots_tallied
  then
    if self.ballots_dropped = other.ballots_dropped
    then
      let b ←
        alloc.vec.partial_eq.PartialEqVec.eq
          alloc.string.String.Insts.CoreCmpPartialEqString self.winners
          other.winners
      if b
      then
        let b1 ←
          alloc.vec.partial_eq.PartialEqVec.eq (core.cmp.PartialEqVec
            RoundCount.Insts.CoreCmpPartialEqRoundCount) self.per_round_counts
            other.per_round_counts
        if b1
        then
          let b2 ←
            alloc.vec.partial_eq.PartialEqVec.eq (core.cmp.PartialEqVec
              alloc.string.String.Insts.CoreCmpPartialEqString)
              self.eliminated_by_round other.eliminated_by_round
          if b2
          then
            let b3 ←
              alloc.vec.partial_eq.PartialEqVec.eq
                alloc.string.String.Insts.CoreCmpPartialEqString
                self.dropped_voters other.dropped_voters
            if b3
            then
              alloc.vec.partial_eq.PartialEqVec.eq
                alloc.string.String.Insts.CoreCmpPartialEqString
                self.non_voters other.non_voters
            else ok false
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::TallyResult> for verified_rcv_enclave_core::TallyResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 114:23-114:32 -/
@[reducible]
def TallyResult.Insts.CoreCmpPartialEqTallyResult : core.cmp.PartialEq
  TallyResult TallyResult := {
  eq := TallyResult.Insts.CoreCmpPartialEqTallyResult.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::TallyResult}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 114:34-114:36
    Visibility: public -/
def TallyResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : TallyResult) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::TallyResult}]
    Source: 'crates/enclave-core/src/lib.rs', lines 114:34-114:36 -/
@[reducible]
def TallyResult.Insts.CoreCmpEq : core.cmp.Eq TallyResult := {
  partialEqInst := TallyResult.Insts.CoreCmpPartialEqTallyResult
  assert_receiver_is_total_eq :=
    TallyResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::DecryptedSet]
    Source: 'crates/enclave-core/src/lib.rs', lines 135:0-139:1
    Visibility: public -/
structure DecryptedSet where
  valid : alloc.vec.Vec (String × Ballot)
  dropped : alloc.vec.Vec String
  non_voters : alloc.vec.Vec String

/-- [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::DecryptedSet}::clone]:
    Source: 'crates/enclave-core/src/lib.rs', lines 134:9-134:14
    Visibility: public -/
def DecryptedSet.Insts.CoreCloneClone.clone
  (self : DecryptedSet) : Result DecryptedSet := do
  let v ←
    alloc.vec.CloneVec.clone (BuiltinClone (String × Ballot)) self.valid
  let v1 ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.dropped
  let v2 ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      self.non_voters
  ok { valid := v, dropped := v1, non_voters := v2 }

/-- Trait implementation: [verified_rcv_enclave_core::{core::clone::Clone for verified_rcv_enclave_core::DecryptedSet}]
    Source: 'crates/enclave-core/src/lib.rs', lines 134:9-134:14 -/
@[reducible]
def DecryptedSet.Insts.CoreCloneClone : core.clone.Clone DecryptedSet := {
  clone := DecryptedSet.Insts.CoreCloneClone.clone
}

/-- [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::DecryptedSet}::fmt]:
    Source: 'crates/enclave-core/src/lib.rs', lines 134:16-134:21
    Visibility: public -/
def DecryptedSet.Insts.CoreFmtDebug.fmt
  (self : DecryptedSet) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugVec (Pair.Insts.CoreFmtDebug
      alloc.string.String.Insts.CoreFmtDebug Ballot.Insts.CoreFmtDebug))
      self.valid
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugVec alloc.string.String.Insts.CoreFmtDebug)
      self.dropped
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
      alloc.string.String.Insts.CoreFmtDebug)) self.non_voters
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "DecryptedSet") (toStr
    "valid") dyn (toStr "dropped") dyn1 (toStr "non_voters") dyn2

/-- Trait implementation: [verified_rcv_enclave_core::{core::fmt::Debug for verified_rcv_enclave_core::DecryptedSet}]
    Source: 'crates/enclave-core/src/lib.rs', lines 134:16-134:21 -/
@[reducible]
def DecryptedSet.Insts.CoreFmtDebug : core.fmt.Debug DecryptedSet := {
  fmt := DecryptedSet.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified_rcv_enclave_core::{core::marker::StructuralPartialEq for verified_rcv_enclave_core::DecryptedSet}]
    Source: 'crates/enclave-core/src/lib.rs', lines 134:23-134:32 -/
@[reducible]
def DecryptedSet.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq DecryptedSet := {
}

/-- [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::DecryptedSet> for verified_rcv_enclave_core::DecryptedSet}::eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 134:23-134:32
    Visibility: public -/
def DecryptedSet.Insts.CoreCmpPartialEqDecryptedSet.eq
  (self : DecryptedSet) (other : DecryptedSet) : Result Bool := do
  let b ←
    alloc.vec.partial_eq.PartialEqVec.eq (Pair.Insts.CoreCmpPartialEqPair
      alloc.string.String.Insts.CoreCmpPartialEqString
      Ballot.Insts.CoreCmpPartialEqBallot) self.valid other.valid
  if b
  then
    let b1 ←
      alloc.vec.partial_eq.PartialEqVec.eq
        alloc.string.String.Insts.CoreCmpPartialEqString self.dropped
        other.dropped
    if b1
    then
      alloc.vec.partial_eq.PartialEqVec.eq
        alloc.string.String.Insts.CoreCmpPartialEqString self.non_voters
        other.non_voters
    else ok false
  else ok false

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::PartialEq<verified_rcv_enclave_core::DecryptedSet> for verified_rcv_enclave_core::DecryptedSet}]
    Source: 'crates/enclave-core/src/lib.rs', lines 134:23-134:32 -/
@[reducible]
def DecryptedSet.Insts.CoreCmpPartialEqDecryptedSet : core.cmp.PartialEq
  DecryptedSet DecryptedSet := {
  eq := DecryptedSet.Insts.CoreCmpPartialEqDecryptedSet.eq
}

/-- [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::DecryptedSet}::assert_receiver_is_total_eq]:
    Source: 'crates/enclave-core/src/lib.rs', lines 134:34-134:36
    Visibility: public -/
def DecryptedSet.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : DecryptedSet) : Result Unit := do
  ok ()

/-- Trait implementation: [verified_rcv_enclave_core::{core::cmp::Eq for verified_rcv_enclave_core::DecryptedSet}]
    Source: 'crates/enclave-core/src/lib.rs', lines 134:34-134:36 -/
@[reducible]
def DecryptedSet.Insts.CoreCmpEq : core.cmp.Eq DecryptedSet := {
  partialEqInst := DecryptedSet.Insts.CoreCmpPartialEqDecryptedSet
  assert_receiver_is_total_eq :=
    DecryptedSet.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified_rcv_enclave_core::addr_in]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 149:4-156:1 -/
@[rust_loop_body]
def addr_in_loop.body
  (xs : alloc.vec.Vec String) (a : String) (n : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < n
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String) xs i
    let b ← alloc.string.String.Insts.CoreCmpPartialEqString.eq s a
    if b
    then ok (done true)
    else let i1 ← i + 1#usize
         ok (cont i1)
  else ok (done false)

/-- [verified_rcv_enclave_core::addr_in]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 149:4-156:1 -/
@[rust_loop]
def addr_in_loop
  (xs : alloc.vec.Vec String) (a : String) (n : Std.Usize) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => addr_in_loop.body xs a n i1)
    i

/-- [verified_rcv_enclave_core::addr_in]:
    Source: 'crates/enclave-core/src/lib.rs', lines 146:0-156:1 -/
def addr_in (xs : alloc.vec.Vec String) (a : String) : Result Bool := do
  let n := alloc.vec.Vec.len xs
  addr_in_loop xs a n 0#usize

/-- [verified_rcv_enclave_core::position_of]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 168:4-175:1 -/
@[rust_loop_body]
def position_of_loop.body
  (needle : String) (haystack : alloc.vec.Vec String) (n : Std.Usize)
  (j : Std.Usize) :
  Result (ControlFlow Std.Usize (Option Std.Usize))
  := do
  if j < n
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String)
        haystack j
    let b ← alloc.string.String.Insts.CoreCmpPartialEqString.eq s needle
    if b
    then ok (done (some j))
    else let j1 ← j + 1#usize
         ok (cont j1)
  else ok (done none)

/-- [verified_rcv_enclave_core::position_of]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 168:4-175:1 -/
@[rust_loop]
def position_of_loop
  (needle : String) (haystack : alloc.vec.Vec String) (n : Std.Usize)
  (j : Std.Usize) :
  Result (Option Std.Usize)
  := do
  loop
    (fun j1 => position_of_loop.body needle haystack n j1)
    j

/-- [verified_rcv_enclave_core::position_of]:
    Source: 'crates/enclave-core/src/lib.rs', lines 165:0-175:1 -/
def position_of
  (needle : String) (haystack : alloc.vec.Vec String) :
  Result (Option Std.Usize)
  := do
  let n := alloc.vec.Vec.len haystack
  position_of_loop needle haystack n 0#usize

/-- [verified_rcv_enclave_core::first_active_index]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 180:4-188:1 -/
@[rust_loop_body]
def first_active_index_loop.body
  (ranking : alloc.vec.Vec String) (remaining : alloc.vec.Vec String)
  (r_len : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option Std.Usize))
  := do
  if i < r_len
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String)
        ranking i
    let idx_opt ← position_of s remaining
    let b := core.option.Option.is_some idx_opt
    if b
    then ok (done idx_opt)
    else let i1 ← i + 1#usize
         ok (cont i1)
  else ok (done none)

/-- [verified_rcv_enclave_core::first_active_index]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 180:4-188:1 -/
@[rust_loop]
def first_active_index_loop
  (ranking : alloc.vec.Vec String) (remaining : alloc.vec.Vec String)
  (r_len : Std.Usize) (i : Std.Usize) :
  Result (Option Std.Usize)
  := do
  loop
    (fun i1 => first_active_index_loop.body ranking remaining r_len i1)
    i

/-- [verified_rcv_enclave_core::first_active_index]:
    Source: 'crates/enclave-core/src/lib.rs', lines 177:0-188:1 -/
def first_active_index
  (ranking : alloc.vec.Vec String) (remaining : alloc.vec.Vec String) :
  Result (Option Std.Usize)
  := do
  let r_len := alloc.vec.Vec.len ranking
  first_active_index_loop ranking remaining r_len 0#usize

/-- [verified_rcv_enclave_core::count_at_index]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 1:0-212:5 -/
@[rust_loop_body]
def count_at_index_loop.body
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  (target_idx : Std.Usize) (n : Std.Usize) (count : Std.Usize) (b : Std.Usize)
  :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  if b < n
  then
    let (_, b1) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
        Ballot)) valid b
    let idx_opt ← first_active_index b1.ranking remaining
    let b2 := core.option.Option.is_some idx_opt
    let count1 ←
      if b2
      then
        do
        let i ← core.option.Option.unwrap idx_opt
        if i = target_idx
        then count + 1#usize
        else ok count
      else ok count
    let b3 ← b + 1#usize
    ok (cont (count1, b3))
  else ok (done count)

/-- [verified_rcv_enclave_core::count_at_index]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 1:0-212:5 -/
@[rust_loop]
def count_at_index_loop
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  (target_idx : Std.Usize) (n : Std.Usize) (count : Std.Usize) (b : Std.Usize)
  :
  Result Std.Usize
  := do
  loop
    (fun (count1, b1) => count_at_index_loop.body valid remaining target_idx n
      count1 b1)
    (count, b)

/-- [verified_rcv_enclave_core::count_at_index]:
    Source: 'crates/enclave-core/src/lib.rs', lines 197:0-214:1 -/
def count_at_index
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  (target_idx : Std.Usize) :
  Result Std.Usize
  := do
  let n := alloc.vec.Vec.len valid
  count_at_index_loop valid remaining target_idx n 0#usize 0#usize

/-- [verified_rcv_enclave_core::tally_round]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 220:4-227:5 -/
@[rust_loop_body]
def tally_round_loop.body
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  (rem_len : Std.Usize) (out : alloc.vec.Vec RoundCount) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec RoundCount) × Std.Usize) (alloc.vec.Vec
    RoundCount))
  := do
  if i < rem_len
  then
    let c ← count_at_index valid remaining i
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String)
        remaining i
    let s1 ← alloc.string.String.Insts.CoreCloneClone.clone s
    let i1 ← lift (UScalar.cast .U32 c)
    let out1 ←
      alloc.vec.Vec.push out ({ candidate := s1, count := i1 } : RoundCount)
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [verified_rcv_enclave_core::tally_round]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 220:4-227:5 -/
@[rust_loop]
def tally_round_loop
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  (rem_len : Std.Usize) (out : alloc.vec.Vec RoundCount) (i : Std.Usize) :
  Result (alloc.vec.Vec RoundCount)
  := do
  loop
    (fun (out1, i1) => tally_round_loop.body valid remaining rem_len out1 i1)
    (out, i)

/-- [verified_rcv_enclave_core::tally_round]:
    Source: 'crates/enclave-core/src/lib.rs', lines 216:0-229:1 -/
def tally_round
  (valid : alloc.vec.Vec (String × Ballot)) (remaining : alloc.vec.Vec String)
  :
  Result (alloc.vec.Vec RoundCount)
  := do
  let rem_len := alloc.vec.Vec.len remaining
  let out := alloc.vec.Vec.with_capacity RoundCount rem_len
  tally_round_loop valid remaining rem_len out 0#usize

/-- [verified_rcv_enclave_core::min_count]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 240:4-245:5 -/
@[rust_loop_body]
def min_count_loop.body
  (rc : alloc.vec.Vec RoundCount) (n : Std.Usize) (m : Std.U32) (i : Std.Usize)
  :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if i < n
  then
    let rc1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice RoundCount) rc
        i
    let m1 ← if rc1.count < m
               then ok rc1.count
               else ok m
    let i1 ← i + 1#usize
    ok (cont (m1, i1))
  else ok (done m)

/-- [verified_rcv_enclave_core::min_count]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 240:4-245:5 -/
@[rust_loop]
def min_count_loop
  (rc : alloc.vec.Vec RoundCount) (n : Std.Usize) (m : Std.U32) (i : Std.Usize)
  :
  Result Std.U32
  := do
  loop
    (fun (m1, i1) => min_count_loop.body rc n m1 i1)
    (m, i)

/-- [verified_rcv_enclave_core::min_count]:
    Source: 'crates/enclave-core/src/lib.rs', lines 233:0-247:1 -/
def min_count (rc : alloc.vec.Vec RoundCount) : Result Std.U32 := do
  let n := alloc.vec.Vec.len rc
  if n = 0#usize
  then ok 0#u32
  else
    let rc1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice RoundCount) rc
        0#usize
    min_count_loop rc n rc1.count 1#usize

/-- [verified_rcv_enclave_core::total_count]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 254:4-257:5 -/
@[rust_loop_body]
def total_count_loop.body
  (rc : alloc.vec.Vec RoundCount) (n : Std.Usize) (s : Std.U32) (i : Std.Usize)
  :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if i < n
  then
    let rc1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice RoundCount) rc
        i
    let s1 ← s + rc1.count
    let i1 ← i + 1#usize
    ok (cont (s1, i1))
  else ok (done s)

/-- [verified_rcv_enclave_core::total_count]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 254:4-257:5 -/
@[rust_loop]
def total_count_loop
  (rc : alloc.vec.Vec RoundCount) (n : Std.Usize) (s : Std.U32) (i : Std.Usize)
  :
  Result Std.U32
  := do
  loop
    (fun (s1, i1) => total_count_loop.body rc n s1 i1)
    (s, i)

/-- [verified_rcv_enclave_core::total_count]:
    Source: 'crates/enclave-core/src/lib.rs', lines 250:0-259:1 -/
def total_count (rc : alloc.vec.Vec RoundCount) : Result Std.U32 := do
  let n := alloc.vec.Vec.len rc
  total_count_loop rc n 0#u32 0#usize

/-- [verified_rcv_enclave_core::candidates_with_count]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 267:4-272:5 -/
@[rust_loop_body]
def candidates_with_count_loop.body
  (rc : alloc.vec.Vec RoundCount) (m : Std.U32) (n : Std.Usize)
  (out : alloc.vec.Vec String) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec String) × Std.Usize) (alloc.vec.Vec
    String))
  := do
  if i < n
  then
    let rc1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice RoundCount) rc
        i
    let out1 ←
      if rc1.count = m
      then
        do
        let s ← alloc.string.String.Insts.CoreCloneClone.clone rc1.candidate
        alloc.vec.Vec.push out s
      else ok out
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [verified_rcv_enclave_core::candidates_with_count]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 267:4-272:5 -/
@[rust_loop]
def candidates_with_count_loop
  (rc : alloc.vec.Vec RoundCount) (m : Std.U32) (n : Std.Usize)
  (out : alloc.vec.Vec String) (i : Std.Usize) :
  Result (alloc.vec.Vec String)
  := do
  loop
    (fun (out1, i1) => candidates_with_count_loop.body rc m n out1 i1)
    (out, i)

/-- [verified_rcv_enclave_core::candidates_with_count]:
    Source: 'crates/enclave-core/src/lib.rs', lines 263:0-274:1 -/
def candidates_with_count
  (rc : alloc.vec.Vec RoundCount) (m : Std.U32) :
  Result (alloc.vec.Vec String)
  := do
  let n := alloc.vec.Vec.len rc
  candidates_with_count_loop rc m n (alloc.vec.Vec.new String) 0#usize

/-- [verified_rcv_enclave_core::first_majority_index]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 281:4-288:1 -/
@[rust_loop_body]
def first_majority_index_loop.body
  (rc : alloc.vec.Vec RoundCount) (threshold : Std.U32) (n : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option Std.Usize))
  := do
  if i < n
  then
    let rc1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice RoundCount) rc
        i
    if rc1.count > threshold
    then ok (done (some i))
    else let i1 ← i + 1#usize
         ok (cont i1)
  else ok (done none)

/-- [verified_rcv_enclave_core::first_majority_index]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 281:4-288:1 -/
@[rust_loop]
def first_majority_index_loop
  (rc : alloc.vec.Vec RoundCount) (threshold : Std.U32) (n : Std.Usize)
  (i : Std.Usize) :
  Result (Option Std.Usize)
  := do
  loop
    (fun i1 => first_majority_index_loop.body rc threshold n i1)
    i

/-- [verified_rcv_enclave_core::first_majority_index]:
    Source: 'crates/enclave-core/src/lib.rs', lines 278:0-288:1 -/
def first_majority_index
  (rc : alloc.vec.Vec RoundCount) (threshold : Std.U32) :
  Result (Option Std.Usize)
  := do
  let n := alloc.vec.Vec.len rc
  first_majority_index_loop rc threshold n 0#usize

/-- [verified_rcv_enclave_core::remove_from]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 296:4-301:5 -/
@[rust_loop_body]
def remove_from_loop.body
  (remaining : alloc.vec.Vec String) (to_remove : alloc.vec.Vec String)
  (n : Std.Usize) (out : alloc.vec.Vec String) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec String) × Std.Usize) (alloc.vec.Vec
    String))
  := do
  if i < n
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String)
        remaining i
    let b ← addr_in to_remove s
    let out1 ←
      if b
      then ok out
      else
        do
        let s1 ← alloc.string.String.Insts.CoreCloneClone.clone s
        alloc.vec.Vec.push out s1
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [verified_rcv_enclave_core::remove_from]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 296:4-301:5 -/
@[rust_loop]
def remove_from_loop
  (remaining : alloc.vec.Vec String) (to_remove : alloc.vec.Vec String)
  (n : Std.Usize) (out : alloc.vec.Vec String) (i : Std.Usize) :
  Result (alloc.vec.Vec String)
  := do
  loop
    (fun (out1, i1) => remove_from_loop.body remaining to_remove n out1 i1)
    (out, i)

/-- [verified_rcv_enclave_core::remove_from]:
    Source: 'crates/enclave-core/src/lib.rs', lines 292:0-303:1 -/
def remove_from
  (remaining : alloc.vec.Vec String) (to_remove : alloc.vec.Vec String) :
  Result (alloc.vec.Vec String)
  := do
  let n := alloc.vec.Vec.len remaining
  remove_from_loop remaining to_remove n (alloc.vec.Vec.new String) 0#usize

/-- [verified_rcv_enclave_core::irv_spec]: loop body 1:
    Source: 'crates/enclave-core/src/lib.rs', lines 394:12-400:13
    Visibility: public -/
@[rust_loop_body]
def irv_spec_loop0_loop0.body
  (candidates : alloc.vec.Vec String) (n_cands : Std.Usize)
  (zero_round : alloc.vec.Vec RoundCount) (zi : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec RoundCount) × Std.Usize) (alloc.vec.Vec
    RoundCount))
  := do
  if zi < n_cands
  then
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String)
        candidates zi
    let s1 ← alloc.string.String.Insts.CoreCloneClone.clone s
    let zero_round1 ←
      alloc.vec.Vec.push zero_round ({ candidate := s1, count := 0#u32 } :
        RoundCount)
    let zi1 ← zi + 1#usize
    ok (cont (zero_round1, zi1))
  else ok (done zero_round)

/-- [verified_rcv_enclave_core::irv_spec]: loop 1:
    Source: 'crates/enclave-core/src/lib.rs', lines 394:12-400:13
    Visibility: public -/
@[rust_loop]
def irv_spec_loop0_loop0
  (candidates : alloc.vec.Vec String) (n_cands : Std.Usize)
  (zero_round : alloc.vec.Vec RoundCount) (zi : Std.Usize) :
  Result (alloc.vec.Vec RoundCount)
  := do
  loop
    (fun (zero_round1, zi1) => irv_spec_loop0_loop0.body candidates n_cands
      zero_round1 zi1)
    (zero_round, zi)

/-- [verified_rcv_enclave_core::irv_spec]: loop body 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 1:0-441:5
    Visibility: public -/
@[rust_loop_body]
def irv_spec_loop0.body
  (candidates : alloc.vec.Vec String)
  (valid_vec : alloc.vec.Vec (String × Ballot)) (max_rounds : Std.Usize)
  (per_round_counts : alloc.vec.Vec (alloc.vec.Vec RoundCount))
  (eliminated_by_round : alloc.vec.Vec (alloc.vec.Vec String))
  (remaining : alloc.vec.Vec String) (round : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (alloc.vec.Vec RoundCount)) ×
    (alloc.vec.Vec (alloc.vec.Vec String)) × (alloc.vec.Vec String) ×
    Std.Usize) ((alloc.vec.Vec (alloc.vec.Vec RoundCount)) × (alloc.vec.Vec
    (alloc.vec.Vec String)) × (alloc.vec.Vec String)))
  := do
  if round >= max_rounds
  then
    let winners ←
      alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
        remaining
    ok (done (per_round_counts, eliminated_by_round, winners))
  else
    let rc ← tally_round valid_vec remaining
    let v ← alloc.vec.CloneVec.clone RoundCount.Insts.CoreCloneClone rc
    let per_round_counts1 ← alloc.vec.Vec.push per_round_counts v
    let i := alloc.vec.Vec.len remaining
    if i = 0#usize
    then
      let winners ←
        alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
          candidates
      ok (done (per_round_counts1, eliminated_by_round, winners))
    else
      let i1 := alloc.vec.Vec.len remaining
      if i1 = 1#usize
      then
        let winners ←
          alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
            remaining
        ok (done (per_round_counts1, eliminated_by_round, winners))
      else
        let total ← total_count rc
        if total = 0#u32
        then
          let n_cands := alloc.vec.Vec.len candidates
          let zero_round := alloc.vec.Vec.with_capacity RoundCount n_cands
          let zero_round1 ←
            irv_spec_loop0_loop0 candidates n_cands zero_round 0#usize
          let i2 := alloc.vec.Vec.len per_round_counts1
          let last_idx ← i2 - 1#usize
          let (_, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              (alloc.vec.Vec RoundCount)) per_round_counts1 last_idx
          let winners ←
            alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
              candidates
          let per_round_counts2 := index_mut_back zero_round1
          ok (done (per_round_counts2, eliminated_by_round, winners))
        else
          let threshold ← total / 2#u32
          let o ← first_majority_index rc threshold
          match o with
          | none =>
            let m ← min_count rc
            let losers ← candidates_with_count rc m
            let i2 := alloc.vec.Vec.len losers
            let i3 := alloc.vec.Vec.len remaining
            if i2 = i3
            then
              let winners ←
                alloc.vec.CloneVec.clone
                  alloc.string.String.Insts.CoreCloneClone remaining
              ok (done (per_round_counts1, eliminated_by_round, winners))
            else
              let v1 ←
                alloc.vec.CloneVec.clone
                  alloc.string.String.Insts.CoreCloneClone losers
              let eliminated_by_round1 ←
                alloc.vec.Vec.push eliminated_by_round v1
              let remaining1 ← remove_from remaining losers
              let round1 ← round + 1#usize
              ok (cont (per_round_counts1, eliminated_by_round1, remaining1,
                round1))
          | some idx =>
            let single_winner := alloc.vec.Vec.with_capacity String 1#usize
            let rc1 ←
              alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
                RoundCount) rc idx
            let s ←
              alloc.string.String.Insts.CoreCloneClone.clone rc1.candidate
            let single_winner1 ← alloc.vec.Vec.push single_winner s
            ok (done (per_round_counts1, eliminated_by_round, single_winner1))

/-- [verified_rcv_enclave_core::irv_spec]: loop 0:
    Source: 'crates/enclave-core/src/lib.rs', lines 1:0-441:5
    Visibility: public -/
@[rust_loop]
def irv_spec_loop0
  (candidates : alloc.vec.Vec String)
  (valid_vec : alloc.vec.Vec (String × Ballot))
  (per_round_counts : alloc.vec.Vec (alloc.vec.Vec RoundCount))
  (eliminated_by_round : alloc.vec.Vec (alloc.vec.Vec String))
  (remaining : alloc.vec.Vec String) (max_rounds : Std.Usize)
  (round : Std.Usize) :
  Result ((alloc.vec.Vec (alloc.vec.Vec RoundCount)) × (alloc.vec.Vec
    (alloc.vec.Vec String)) × (alloc.vec.Vec String))
  := do
  loop
    (fun (per_round_counts1, eliminated_by_round1, remaining1, round1) =>
      irv_spec_loop0.body candidates valid_vec max_rounds per_round_counts1
      eliminated_by_round1 remaining1 round1)
    (per_round_counts, eliminated_by_round, remaining, round)

/-- [verified_rcv_enclave_core::irv_spec]:
    Source: 'crates/enclave-core/src/lib.rs', lines 314:0-449:1
    Visibility: public -/
def irv_spec
  (valid : Slice (String × Ballot)) (candidates : alloc.vec.Vec String) :
  Result IRVResult
  := do
  let i := Slice.len valid
  let ballots_tallied ← lift (UScalar.cast .U32 i)
  let valid_vec ←
    alloc.slice.Slice.to_vec (BuiltinClone (String × Ballot)) valid
  let remaining ←
    alloc.vec.CloneVec.clone alloc.string.String.Insts.CoreCloneClone
      candidates
  let i1 := alloc.vec.Vec.len candidates
  if i1 = 0#usize
  then
    ok
      {
        winners := (alloc.vec.Vec.new String),
        per_round_counts := (alloc.vec.Vec.new (alloc.vec.Vec RoundCount)),
        eliminated_by_round := (alloc.vec.Vec.new (alloc.vec.Vec String)),
        ballots_tallied
      }
  else
    let i2 := alloc.vec.Vec.len candidates
    let max_rounds ← i2 + 1#usize
    let (per_round_counts, eliminated_by_round, winners) ←
      irv_spec_loop0 candidates valid_vec (alloc.vec.Vec.new (alloc.vec.Vec
        RoundCount)) (alloc.vec.Vec.new (alloc.vec.Vec String)) remaining
        max_rounds 0#usize
    ok { winners, per_round_counts, eliminated_by_round, ballots_tallied }

/-- [verified_rcv_enclave_core::decrypt_and_validate]:
    Source: 'crates/enclave-core/src/lib.rs', lines 455:0-464:1
    Visibility: public -/
def decrypt_and_validate
  (_raw : alloc.vec.Vec RawEntry) (_candidates : alloc.vec.Vec String)
  (_privkey : alloc.vec.Vec Std.U8) :
  Result DecryptedSet
  := do
  fail panic

/-- [verified_rcv_enclave_core::tally_spec]:
    Source: 'crates/enclave-core/src/lib.rs', lines 469:0-486:1
    Visibility: public -/
def tally_spec
  (raw1 : alloc.vec.Vec RawEntry) (candidates : alloc.vec.Vec String)
  (privkey : alloc.vec.Vec Std.U8) :
  Result TallyResult
  := do
  let d ← decrypt_and_validate raw1 candidates privkey
  let s := alloc.vec.Vec.deref d.valid
  let r ← irv_spec s candidates
  let i := alloc.vec.Vec.len d.dropped
  let ballots_dropped ← lift (UScalar.cast .U32 i)
  ok
    {
      winners := r.winners,
      per_round_counts := r.per_round_counts,
      eliminated_by_round := r.eliminated_by_round,
      ballots_tallied := r.ballots_tallied,
      ballots_dropped,
      dropped_voters := d.dropped,
      non_voters := d.non_voters
    }

end verified_rcv_enclave_core
